# Tensor Operations and Functions

### Getting familiar with the Pytorch Tensor class

Getting started on the most basic of what's needed for the deep learning course by learning about tensors and their properties in PyTorch

The functions we will be looking at are:
- torch.FloatTensor.abs()
- new_zeros()
- torch.add()
- torch.argmax()
- torch.floor()/torch.ceil()

In [2]:
# Import torch and other required modules
import torch

## Function 1 - torch.FloatTensor.abs()

This function basically returns the arguement tensor converted to its absolute float value and reassingned

In [3]:
# Example 1 - working 
tensor1 = torch.tensor([[1, 2], [3, 4.]])

tensor2 = torch.FloatTensor.abs(tensor1)

print(tensor1)
print(tensor2)

tensor([[1., 2.],
        [3., 4.]])
tensor([[1., 2.],
        [3., 4.]])


Well we had this as a float tensor as default and the function returns the same tensor as there are no negative values

In [4]:
# Example 2 - working
tensor1 = torch.tensor([[-1., -20.], 
                        [-45., 67.]])

tensor2 = torch.FloatTensor.abs(tensor1)

print(tensor1)
print(tensor2)

tensor([[ -1., -20.],
        [-45.,  67.]])
tensor([[ 1., 20.],
        [45., 67.]])


Here the tensor we have chosen has some negative values so we can analyse the function...

In [6]:
# Example 3 - breaking (to illustrate when it breaks)
tensor1 = torch.tensor([[23., -7., 9.], [33.]], dtype = torch.int32)

tensor2 = torch.FloatTensor.abs(tensor1)

ValueError: expected sequence of length 3 at dim 1 (got 1)

The only problem here is that the dimensions for the first element in tensor1 is mismatched with respect to the second element

This function is used to convert the elements of a tensor to their absolute values.

## Function 2 - new_zeros()

This function creates a new tensor filled with zeros.

In [14]:
# Example 1 - working
tensor1 = torch.tensor(())

tensor2 = tensor1.new_zeros((4,5,7,8,9,9))
print(tensor2)

tensor([[[[[[0., 0., 0.,  ..., 0., 0., 0.],
            [0., 0., 0.,  ..., 0., 0., 0.],
            [0., 0., 0.,  ..., 0., 0., 0.],
            ...,
            [0., 0., 0.,  ..., 0., 0., 0.],
            [0., 0., 0.,  ..., 0., 0., 0.],
            [0., 0., 0.,  ..., 0., 0., 0.]],

           [[0., 0., 0.,  ..., 0., 0., 0.],
            [0., 0., 0.,  ..., 0., 0., 0.],
            [0., 0., 0.,  ..., 0., 0., 0.],
            ...,
            [0., 0., 0.,  ..., 0., 0., 0.],
            [0., 0., 0.,  ..., 0., 0., 0.],
            [0., 0., 0.,  ..., 0., 0., 0.]],

           [[0., 0., 0.,  ..., 0., 0., 0.],
            [0., 0., 0.,  ..., 0., 0., 0.],
            [0., 0., 0.,  ..., 0., 0., 0.],
            ...,
            [0., 0., 0.,  ..., 0., 0., 0.],
            [0., 0., 0.,  ..., 0., 0., 0.],
            [0., 0., 0.,  ..., 0., 0., 0.]],

           ...,

           [[0., 0., 0.,  ..., 0., 0., 0.],
            [0., 0., 0.,  ..., 0., 0., 0.],
            [0., 0., 0.,  ..., 0., 0., 0.],
  

We create a tensor of dimensions given in the new_zeros() 

In [15]:
# Example 2 - working
tensor1 = torch.tensor((), dtype = torch.int32)

tensor2 = tensor1.new_zeros((3, 4, 2))

print(tensor2)

tensor([[[0, 0],
         [0, 0],
         [0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0],
         [0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0],
         [0, 0],
         [0, 0]]], dtype=torch.int32)


The data type of tensor2 is specified in this example using tensor1.

In [16]:
# Example 3 - breaking (to illustrate when it breaks)
tensor1 = torch.tensor([[3, 4, 5, 6], [45, 72]], dtype = torch.float64)

tensor2 = tensor1.new_zeros((7, 4))

ValueError: expected sequence of length 4 at dim 1 (got 2)

The problem here is that the dimensions of tensor1 are mismatched and hence the compiler throws out this error.

We can use this function to generate a tensor filled with zeros with our desired data type.

## Function 3 - torch.add()

This function adds a scalar to a tensor(usually a multi dimensional matrix)

In [18]:
# Example 1 - working
tensor1 = torch.tensor([[31, 45, 16], [5, 92, 63]], dtype = torch.int32)

torch.add(tensor1, 18, out = None)

tensor([[ 49,  63,  34],
        [ 23, 110,  81]], dtype=torch.int32)

The above function simply adds 18 to all the elements of tensor1 and shows us the result.

In [20]:
# Example 2 - working
tensor1 = torch.tensor([[3.45, 6.7], [6.88, 9]], dtype = torch.float64)

tensor2 = torch.add(tensor1, 6.9, out = None)

print(tensor2)

tensor([[10.3500, 13.6000],
        [13.7800, 15.9000]], dtype=torch.float64)


The function can also make floating point addition.

In [22]:
# Example 3 - breaking (to illustrate when it breaks)
tensor1 = torch.tensor([[3.45, 6.7], [6.88, 9]], dtype = torch.float64)

tensor2 = torch.add(tensor1, 6.9+4.1j, out = None)

print(tensor2)

RuntimeError: Complex dtype not supported.

Well, we can add real numbers to integers but we cannot add complex numbers to real numbers using this function.

This function is handy in the sense that it allows us to add some real numbers to a tensor.

## Function 4 - torch.argmax()

This function returns the index of the largest value in our tensor.

In [24]:
# Example 1 - working
tensor1 = torch.tensor([[13, 333], [666, 420]], dtype = torch.int64)

print(tensor1)

print(torch.argmax(tensor1))

tensor([[ 13, 333],
        [666, 420]])
tensor(2)


The function computes the largest element in the tensor and prints out its index

In [28]:
# Example 2 - working
tensor1 = torch.randn(4, 4, 2)

print(tensor1)

max_dim_2 = torch.argmax(tensor1, dim = 2)

print(max_dim_2)

tensor([[[ 0.4974, -0.3558],
         [ 0.5389, -0.9661],
         [ 1.6667, -1.1505],
         [ 0.9438,  1.1788]],

        [[ 1.3123,  0.3053],
         [ 0.1370, -1.6594],
         [-0.8197, -0.6668],
         [ 1.0095,  0.7181]],

        [[-0.2232, -0.2473],
         [ 0.0829,  0.5004],
         [ 0.6572,  0.0199],
         [-1.2986,  1.1289]],

        [[ 0.1431, -0.3463],
         [-0.2227, -2.0346],
         [-1.1759,  0.3781],
         [ 0.9583, -0.7805]]])
tensor([[0, 0, 0, 1],
        [0, 0, 1, 0],
        [0, 1, 0, 1],
        [0, 0, 1, 0]])


Here we specify the dimension across which we wanna compute argmax and get the value returned.

In [29]:
# Example 3 - breaking (to illustrate when it breaks)
tensor1 = torch.tensor([1])

print(tensor1)

print(torch.argmax(tensor1, dim = 3))

tensor([1])


IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 3)

The indices that we can specify has to be within bounds of the tensor that we input.

This function is used when we want to find the indices of the largest/maximum value elements in a tensor.

## Function 5 - torch.ceil()/torch.floor()

These functions take the floating point tensors and round them off.

In [32]:
# Example 1 - working
tensor1 = torch.tensor([[[34.66, 63.45], [14.4, 56.78]], [[69.69, 42.42], [96.96, 24.24]], [[16.18, 6.81], [69.420, 42.069]]], dtype = torch.float64)

print(tensor1)

print(torch.ceil(tensor1))

tensor([[[34.6600, 63.4500],
         [14.4000, 56.7800]],

        [[69.6900, 42.4200],
         [96.9600, 24.2400]],

        [[16.1800,  6.8100],
         [69.4200, 42.0690]]], dtype=torch.float64)
tensor([[[35., 64.],
         [15., 57.]],

        [[70., 43.],
         [97., 25.]],

        [[17.,  7.],
         [70., 43.]]], dtype=torch.float64)


The ceil function rounds the real number to next largest integer and it is demonstrated here.

In [33]:
# Example 2 - working
tensor1 = torch.tensor([[[34.66, 63.45], [14.4, 56.78]], [[69.69, 42.42], [96.96, 24.24]], [[16.18, 6.81], [69.420, 42.069]]], dtype = torch.float64)

print(tensor1)

print(torch.floor(tensor1))

tensor([[[34.6600, 63.4500],
         [14.4000, 56.7800]],

        [[69.6900, 42.4200],
         [96.9600, 24.2400]],

        [[16.1800,  6.8100],
         [69.4200, 42.0690]]], dtype=torch.float64)
tensor([[[34., 63.],
         [14., 56.]],

        [[69., 42.],
         [96., 24.]],

        [[16.,  6.],
         [69., 42.]]], dtype=torch.float64)


The floor() function converts the real number to lower integer and it is demonstrated here.

In [34]:
# Example 3 - breaking (to illustrate when it breaks)
# Example 2 - working
tensor1 = torch.tensor([[[34.66+9j, 63.45], [14.4, 56.78]], [[69.69, 42.42], [96.96, 24.24]], [[16.18, 6.81], [69.420, 42.069]]], dtype = torch.float64)

print(tensor1)

print(torch.floor(tensor1))
print(torch.ceil(tensor1))

TypeError: can't convert complex to float

The main problem with these ceil() and floor() is that we cant work with complex numbers

Closing comments about when to use this function

## Conclusion

Summarize what was covered in this notebook, and where to go next

## Reference Links
Here are some interesting references about pytorch and tensors in general.
* Official documentation for `torch.Tensor`: https://pytorch.org/docs/stable/tensors.html
* https://medium.com/analytics-vidhya/introduction-to-pytorch-e5df512b1079
* https://towardsdatascience.com/what-is-pytorch-a84e4559f0e3

In [17]:
!pip install jovian --upgrade --quiet

In [18]:
import jovian

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
